# A default 'custom.py' file suitable for 2D games.
#
# NOTE: Generated by https://godot-build-options-generator.github.io, then
# hand-edited. Regenerating reintroduces 'deprecated = "no"', which stops any
# GDExtension built against an older godot-cpp from loading.

disable_3d = "yes"
minizip = "no"
module_camera_enabled = "no"
module_csg_enabled = "no"
module_dds_enabled = "no"
module_enet_enabled = "no"
module_gltf_enabled = "no"
module_hdr_enabled = "no"
module_jsonrpc_enabled = "no"
module_mbedtls_enabled = "no"
module_meshoptimizer_enabled = "no"
module_mobile_vr_enabled = "no"
module_multiplayer_enabled = "no"
module_navigation_2d_enabled = "no"
module_navigation_3d_enabled = "no"
module_upnp_enabled = "no"
module_vhacd_enabled = "no"
module_webrtc_enabled = "no"
module_websocket_enabled = "no"
module_webxr_enabled = "no"