config.extends = "gdbuild.ci.toml"

[godot]
  version_file = ".godot-version"

[target.client]
  runnable = true

  pack_files = [
    {include = ["icon.svg", "core", "maps"], embed = true, encrypt = true},
  ]

[target.client.profile.release]
  encrypt = true # Specify via 'SCRIPT_AES256_ENCRYPTION_KEY' environment variable.

[target.client.platform.macos]
  bundle_identifier = "com.coffeebeats.MY_GAME_NAME"

[[target.client.platform.macos.feature.steam.pack_files]]
  include = ["addons/godotsteam"]
  exclude = ["addons/godotsteam/linux*/", "addons/godotsteam/win*/"]
  embed   = true
  encrypt = true

[[target.client.platform.windows.feature.steam.pack_files]]
  include = ["addons/godotsteam"]
  exclude = ["addons/godotsteam/linux*/", "addons/godotsteam/osx"]
  embed   = true
  encrypt = true

[template]
  custom_py_path = "custom.py"
