name: "🤖 Export: Godot project"

on:
  workflow_call:
    inputs:
      platform:
        type: string
        required: true
      arch:
        type: string
        required: true
      storefront:
        type: string
        required: true
      profile:
        type: string
        required: true
    outputs:
      path:
        description: "The path to the directory containing release artifacts."
        value: ${{ jobs.package.outputs.path }}
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        description: "The platform to target."
        required: true
        default: windows
        options:
          - macos
          - windows
      arch:
        type: choice
        description: "The CPU architecture to target."
        required: true
        default: x86_64
        options:
          - x86_64
          - universal
      storefront:
        type: choice
        description: "The distribution storefront to target."
        required: true
        default: unknown
        options:
          - unknown
          - steam
      profile:
        type: choice
        description: "The optimization profile of the compiled export template."
        required: false
        default: release
        options:
          - release
          - release_debug
          - debug

jobs:
  config:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    outputs:
      presets: ${{ steps.set-presets.outputs.value }}
      godot-version: "${{ steps.version.outputs.semantic }}"

    steps:
      - uses: actions/checkout@v4

      - uses: "coffeebeats/godot-infra/.github/actions/parse-godot-version@main" # TODO: Pin to 'v0'.
        id: version
        with:
          gdenv-pin-path: .godot-version

      - name: Evaluate presets
        id: set-presets
        shell: bash
        run: |-
          PRESETS=($(grep '^name=' export_presets.cfg | sed 's/name=//' | sed 's/"//g' | grep ${{ inputs.storefront }} | grep ${{ inputs.arch }}))
          echo value=$(jq -c -n '$ARGS.positional' --args "${PRESETS[@]}") >> $GITHUB_OUTPUT

  compile:
    needs: ["config"]

    runs-on: ubuntu-latest
    timeout-minutes: 75

    outputs:
      key: ${{ steps.cache.outputs.key }}
      path: ${{ steps.cache.outputs.path }}

    steps:
      - uses: actions/checkout@v4

      - uses: "coffeebeats/godot-infra/compile-godot-export-template@main" # TODO: Pin to 'v0'.
        id: compile
        with:
          godot-src-rev: ${{ needs.config.outputs.godot-version }}

          platform: ${{ inputs.platform }}
          arch: ${{ inputs.arch }}

          custompy-path: ./custom.py
          icon-path: ./icon.svg
          profile: ${{ inputs.profile }}
          use-double-precision: false

          # FIXME: Set secrets for the project.
          encryption-key: ""

      # -------------------- Save export template artifact ------------------- #

      # NOTE: Rather than pass the export template between jobs as an artifact,
      # use the 'actions/cache' action, which is faster for small files.

      - name: Identify the export template file name
        id: export-template
        shell: bash
        run: |-
          TEMPLATE_NAME="$(basename ${{ steps.compile.outputs.path }})"

          echo name="$TEMPLATE_NAME" >> $GITHUB_OUTPUT

      - name: Move the export template to the cache directory
        id: cache
        shell: bash
        run: |-
          TARGET="${{ runner.temp }}/build/${{ steps.export-template.outputs.name }}"

          echo "Moving compiled export template to inter-job cache."
          echo "Source file: ${{ steps.compile.outputs.path }}"
          echo "Destination file: $TARGET"

          mkdir -p ${{ runner.temp }}/build
          sudo mv ${{ steps.compile.outputs.path }} ${{ runner.temp }}/build

          ls ${{ runner.temp }}/build

          echo path="$TARGET" >> $GITHUB_OUTPUT
          echo key='compile-${{ hashFiles(format('{0}/build/{1}', runner.temp, steps.export-template.outputs.name)) }}' >> $GITHUB_OUTPUT

      - name: Cache the export template to pass between jobs
        uses: actions/cache/save@v3
        with:
          key: ${{ steps.cache.outputs.key }}
          path: ${{ steps.cache.outputs.path }}

  export:
    needs: ["config", "compile"]

    runs-on: ubuntu-latest
    timeout-minutes: 15

    outputs:
      key: ${{ steps.cache.outputs.key }}
      path: ${{ steps.cache.outputs.path }}

    strategy:
      fail-fast: true

      # NOTE: Using artifacts for exported binaries will cause them to lose
      # permissions. To avoid this, use a cache action to pass files. However,
      # there's no easy way to assemble the set of cache keys and paths. The
      # easiest solution is to limit concurrency so that each matrix element
      # can sequentially build up a directory of files.
      max-parallel: 1

      matrix:
        preset: ${{ fromJson(needs.config.outputs.presets) }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/cache/restore@v3
        with:
          key: ${{ needs.compile.outputs.key }}
          path: ${{ needs.compile.outputs.path }}

      # ---------------------- Export required presets --------------------- #

      # Main executable
      - uses: "coffeebeats/godot-infra/export-godot-project-preset@main" # TODO: Pin to 'v0'.
        id: export
        with:
          preset-name: "${{ matrix.preset }}"

          godot-editor-version: ${{ needs.config.outputs.godot-version }}
          export-template-path: ${{ needs.compile.outputs.path }}

          profile: ${{ inputs.profile }}

          # FIXME: Set secrets for the project.
          encryption-key: ""

          # Windows
          codesign-identity-type: ""
          codesign-identity: ""
          codesign-password: ""

          # MacOS
          codesign-certificate-file: ""
          codesign-certificate-password: ""
          codesign-provisioning-profile: ""
          notarization-api-uuid: ""
          notarization-api-key: ""
          notarization-api-key-id: ""
          notarization-apple-id-name: ""
          notarization-apple-id-password: ""

      # ----------------------- Save exported artifacts ---------------------- #

      # NOTE: Rather than pass the exported files between jobs as an artifact,
      # use the 'actions/cache' action, which is faster for small files.

      - name: Identify the exported artifact file name
        id: export-preset
        shell: bash
        run: echo path="$(realpath --relative-to $PWD ${{ steps.export.outputs.path }})" >> $GITHUB_OUTPUT

      - uses: actions/cache/restore@v3
        with:
          key: export-${{ hashFiles(format('{0}', steps.export.outputs.path)) }}
          path: ${{ runner.temp }}/dist

      - name: Move the exported artifact to the cache directory
        id: cache
        shell: bash
        run: |-
          TARGET="${{ runner.temp }}/dist/${{ steps.export-preset.outputs.path }}"

          echo "Moving exported artifact to inter-job cache."
          echo "Source file: ${{ steps.export.outputs.path }}"
          echo "Destination file: ${{ runner.temp }}/${{ steps.export-preset.outputs.path }}"

          if [[ -f "$TARGET" ]] || [[ -d "$TARGET" ]]; then
            echo "Unexpectedly found target file: $TARGET"
            exit 1
          fi

          TARGET_DIR="$(dirname "$TARGET")"

          mkdir -p $TARGET_DIR
          sudo mv ${{ steps.export.outputs.path }} $TARGET_DIR

          ls $TARGET_DIR

          echo path="${{ runner.temp }}/dist" >> $GITHUB_OUTPUT
          echo key='export-${{ hashFiles(format('{0}', steps.export.outputs.path)) }}' >> $GITHUB_OUTPUT

      - name: Cache the exported artifacts to pass between jobs
        uses: actions/cache/save@v3
        with:
          key: export-${{ hashFiles(format('{0}', steps.export.outputs.path)) }}
          path: ${{ runner.temp }}/dist

  package:
    needs: ["export"]

    outputs:
      path: ${{ needs.export.outputs.path }}

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/cache/restore@v3
        with:
          key: ${{ needs.export.outputs.key }}
          path: ${{ needs.export.outputs.path }}

      - uses: actions/upload-artifact@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          name: "game-${{ inputs.arch }}-${{ inputs.platform }}-${{ inputs.storefront }}-${{ inputs.profile }}"
          path: ${{ needs.export.outputs.path }}
