name: "🪟 Export: Godot project preset (Windows)"

on:
  workflow_call:
    inputs:
      preset-name:
        type: string
        required: true
      preset-output-name:
        type: string
        required: true
      pck-only:
        type: boolean
        required: false
        default: false
      profile:
        type: string
        required: false
        default: release
      timeout:
        type: number
        required: false
        default: 60
  workflow_dispatch:
    inputs:
      preset-name:
        type: string
        description: "The name of the Godot project export preset."
        required: true
      preset-output-name:
        type: string
        description: "The output filename of the exported Godot project preset."
        required: true
      pck-only:
        type: boolean
        description: "Whether to export a PCK file instead of an executable."
        required: false
        default: false
      profile:
        type: choice
        description: "The optimization profile of the compiled export template."
        required: false
        default: debug
        options:
          - debug
          - release_debug
          - release
      timeout:
        type: number
        description: "The workflow's maximum allowed run duration (in minutes)."
        required: false
        default: 60

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      # TODO: Once testing completes, pin this to 'v0'.
      - uses: "coffeebeats/godot-infra/.github/actions/parse-godot-version@main"
        id: version
        with:
          gdenv-pin-path: .godot-version

      # TODO: Once testing completes, pin this to 'v0'.
      - uses: "coffeebeats/godot-infra/compile-godot-export-template@main"
        id: export-template
        with:
          godot-src-rev: ${{ steps.version.outputs.semantic }}

          arch: x86_64
          platform: windows

          custompy-path: ./custom.py
          profile: ${{ inputs.profile }}
          use-double-precision: false

          # Windows-specific inputs.
          icon-path: ./icon.svg

          # FIXME: Set secrets for the project.
          encryption-key: ""

      # TODO: Once testing completes, pin this to 'v0'.
      - uses: "coffeebeats/godot-infra/export-godot-project-preset@main"
        with:
          preset-name: ${{ inputs.preset-name }}
          preset-output-name: ${{ inputs.preset-output-name }}
          pck-only: ${{ inputs.pck-only }}

          godot-editor-version: ${{ steps.version.outputs.semantic }}
          export-template-artifact-name: ${{ steps.export-template.outputs.name }}

          profile: ${{ inputs.profile }}

          # FIXME: Set secrets for the project.
          encryption-key: ""
          codesign-identity-type: ""
          codesign-identity: ""
          codesign-password: ""
