name: "🔧 Utilities: Optimize PNG image files"

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    outputs:
      added-files: "${{ steps.check-png.outputs.added_files }}"
      modified-files: "${{ steps.check-png.outputs.modified_files }}"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for source icon changes
        id: check-png
        uses: tj-actions/changed-files@v44
        with:
          files: "**/*.png"

  optimize:
    needs: ["changes"]
    if:
      (needs.changes.outputs.added-files != '' || needs.changes.outputs.modified-files != '') &&
      github.actor != 'dependabot[bot]'

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          # Checkout the "head_ref" (i.e. PR branch HEAD) in case a commit is
          # later needed. See https://github.com/stefanzweifel/git-auto-commit-action
          # for more details.
          ref: ${{ github.head_ref }}

      - name: Install 'gdenv'
        uses: coffeebeats/gdenv/.github/actions/setup-gdenv@main

      - name: Install 'pngcrush' tool
        run: apt-get install -y pngcrush

      - name: Optimize images
        run: |
          for f in "${{ needs.changes.outputs.added-files }} ${{ needs.changes.outputs.modified-files }}"; do
            echo "$(du -sh $f) (before)"
            pngcrush "$f" "$f.opt"
            mv "$f.opt" "$f"
            echo "$(du -sh $f) (after)"
          done

      - name: Import optimized images
        run: godot --editor --headless --quit

      - name: Commit changes
        run: |
          if [[ "$(git status --porcelain)" == "" ]]; then
            echo "No changes found; exiting without committing."
            exit 0
          fi

          # See https://github.com/orgs/community/discussions/26560#discussioncomment-3531273
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          git add --all .
          git commit -m "chore: optimizing PNG images (on behalf of '${{ github.triggering_actor }}')"

          git push
