name: "🚀 Release: Project version"

on:
  push:
    branches:
      - main

# NOTE: These permissions only affect the default `GITHUB_TOKEN`. These are left
# here in case the `release-please` action no longer uses a PAT.
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    outputs:
      release-created: ${{ steps.release.outputs.releases_created }}
      release-tag: ${{ steps.release.outputs.tag_name }}

    steps:
      - uses: actions/checkout@v4

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .release-please/config.json
          manifest-file: .release-please/manifest.json

          # NOTE: To handle releases on specific branches (e.g. a '1.X' release branch),
          # simply change the "branches" filter in the workflow's on-"push" trigger.
          target-branch: ${{ github.ref_name }}

          # NOTE: Because 'release-please' is configured to update version text within
          # '.github/workflows/publish-game.yaml', a PAT is required. This PAT must have
          # 'contents:write' and 'workflows:write'; for details, see
          # https://github.com/orgs/community/discussions/35410#discussioncomment-7645702.
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      - name: Log release-please action output
        shell: bash
        env:
          # See https://github.com/actions/runner/issues/1656#issuecomment-1030077729.
          RELEASE_INFO: ${{ toJson(steps.release.outputs) }}
        run: echo $RELEASE_INFO

  publish:
    needs: ["release-please"]
    if: needs.release-please.outputs.release-created == 'true'

    strategy:
      fail-fast: false
      max-parallel: 2

      matrix:
        include:
          - arch: universal
            platform: macos
            storefront: unknown

          - arch: universal
            platform: macos
            storefront: steam

          - arch: wasm32
            platform: web
            storefront: unknown
            publish-to-itchio: true
            itchio-project: "Example" # FIXME: Change to current project name.
            itchio-channel: "release"

          - arch: x86_64
            platform: windows
            storefront: unknown

          - arch: x86_64
            platform: windows
            storefront: steam

    uses: "./.github/workflows/publish-game.yaml"
    with:
      arch: ${{ matrix.arch }}
      platform: ${{ matrix.platform }}
      profile: "release"
      release-tag: ${{ needs.release-please.outputs.release-tag }}
      storefront: ${{ matrix.storefront }}

      # itch.io inputs
      publish-to-itchio: ${{ matrix.publish-to-itchio || false }}
      itchio-project: ${{ matrix.itchio-project }}
      itchio-channel: ${{ matrix.itchio-channel }}

  upload:
    needs: ["release-please", "publish"]
    if: needs.release-please.outputs.release-created == 'true'

    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          pattern: "game-*" # NOTE: This pattern must match the prior workflow.
          path: ${{ runner.temp }}/dist
          merge-multiple: true

      - name: Attach assets to release
        shell: bash
        run: |-
          # Set options to enable more extensive globbing.
          shopt -s extglob
          shopt -s globstar

          ASSETS=(${{ runner.temp }}/dist/*)
          TAG="${{ needs.release-please.outputs.release-tag }}"

          for ASSET in "${ASSETS[@]}"; do
            echo "Attaching asset to release '$TAG': $ASSET"

            gh release upload \
              --clobber \
              ${{ needs.release-please.outputs.release-tag }} \
              $ASSET
          done
