name: "🚀 Release: Project version"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    outputs:
      release-created: ${{ steps.release.outputs.releases_created }}
      release-tag: ${{ steps.release.outputs.tag_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Update 'release-please' configuration (test)
        shell: bash
        run: |
          cat <<EOM >>update.py
          from json import dump,load

          with open('.release-please-config.json') as f:
              data = load(f)
              data["versioning"] = "default"
              data["prerelease"] = False

          with open('.release-please-config.json', 'w') as f:
              dump(data, f)
          EOM

          cat .release-please-config.json

      - name: Commit changes (test)
        run: |
          if [[ "$(git status --porcelain)" == "" ]]; then
            echo "No changes found; exiting without committing."
            exit 0
          fi

          # See https://github.com/orgs/community/discussions/26560#discussioncomment-3531273
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          git add --all .
          git commit -m "chore: temporarily modifying release configuration (on behalf of '${{ github.triggering_actor }}')"

      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

          # NOTE: To handle releases on specific branches (e.g. a '1.X' release branch),
          # simply change the "branches" filter in the workflow's on-"push" trigger.
          target-branch: ${{ github.ref_name }}

      - name: Log release-please action output
        shell: bash
        env:
          # See https://github.com/actions/runner/issues/1656#issuecomment-1030077729.
          RELEASE_INFO: ${{ toJson(steps.release.outputs) }}
        run: echo $RELEASE_INFO
