name: "🚀 Release: Project version"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    outputs:
      release-created: ${{ steps.release.outputs.releases_created }}
      release-tag: ${{ steps.release.outputs.tag_name }}

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

          # NOTE: To handle releases on specific branches (e.g. a '1.X' release branch),
          # simply change the "branches" filter in the workflow's on-"push" trigger.
          target-branch: ${{ github.ref_name }}

      - name: Log release-please action output
        shell: bash
        env:
          # See https://github.com/actions/runner/issues/1656#issuecomment-1030077729.
          RELEASE_INFO: ${{ toJson(steps.release.outputs) }}
        run: echo $RELEASE_INFO

  export:
    needs: ["release-please"]
    if: needs.release-please.outputs.release-created == 'true'

    strategy:
      fail-fast: false
      max-parallel: 2

      matrix:
        include:
          - arch: universal
            platform: macos
            storefront: unknown

          - arch: wasm32
            platform: web
            storefront: unknown

          - arch: x86_64
            platform: windows
            storefront: unknown

    uses: "./.github/workflows/export-project.yaml"
    with:
      arch: ${{ matrix.arch }}
      platform: ${{ matrix.platform }}
      storefront: ${{ matrix.storefront }}
      profile: "release"

  upload:
    needs: ["release-please", "export"]
    if: needs.release-please.outputs.release-created == 'true'

    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          pattern: "game-*" # NOTE: This pattern must match the prior workflow.
          path: ${{ runner.temp }}/dist
          merge-multiple: true

      - name: Attach assets to release
        shell: bash
        run: |-
          # Set options to enable more extensive globbing.
          shopt -s extglob
          shopt -s globstar

          ASSETS=(${{ runner.temp }}/dist/*)
          TAG="${{ needs.release-please.outputs.release-tag }}"

          for ASSET in "${ASSETS[@]}"; do
            echo "Attaching asset to release '$TAG': $ASSET"

            gh release upload \
              --clobber \
              ${{ needs.release-please.outputs.release-tag }} \
              $ASSET
          done

  publish-itchio:
    needs: ["release-please", "upload"]
    if: needs.release-please.outputs.release-created == 'true'

    uses: "./.github/workflows/publish-game.yaml"
    secrets: "inherit"
    with:
      release-tag: "${{ needs.release-please.outputs.release-tag }}"
      platform: "web"
      arch: "wasm32"
      storefront: "unknown"
      profile: "release"

      # itch.io inputs
      publish-to-itchio: true
      itchio-project: "Example" # FIXME: Change to current project name.
      itchio-channel: "release"
